[package]
name = "build-info-common"
version = "0.0.27"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2021"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"
description = "Part of the build-info and build-info-build crates: This crate provides the types that are serialized by build-info-build and used by build-info."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[dependencies]
chrono = { version = "0.4", default_features = false, features = ["std", "alloc", "clock"] }
derive_more = "0.99"
pyo3 = { version = "0.16", optional = true }
semver = "1"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
enable-pyo3 = ["pyo3"]
enable-serde = ["serde", "semver/serde", "chrono/serde"]
